version: '3'

services:
  go:
    container_name: go
    image: golang:1.21.6
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    environment:
      - TZ=Asia/Tokyo
      - GOPATH=/go
